In [2]:
!pip install pandas

     --------------------------------------- 11.6/11.6 MB 10.1 MB/s eta 0:00:00
     -------------------------------------- 345.4/345.4 KB 7.1 MB/s eta 0:00:00
     ------------------------------------- 505.5/505.5 KB 10.5 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\Jaison\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

ModuleNotFoundError: No module named 'sklearn'

In [4]:
!pip install scikit-learn

     --------------------------------------- 11.0/11.0 MB 10.1 MB/s eta 0:00:00
     -------------------------------------- 301.8/301.8 KB 9.4 MB/s eta 0:00:00
     ---------------------------------------- 46.2/46.2 MB 7.3 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\Jaison\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [14]:

df = pd.read_csv(r"C:\Users\Jaison\Downloads\hiring.csv")

In [15]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
df.describe

<bound method NDFrame.describe of   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000>

In [19]:
df.dtypes

experience                     object
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [20]:

df.shape

(8, 4)

In [21]:
for column in df:
                print(f'{column}: {df[column].unique()}')
     

experience: [nan 'five' 'two' 'seven' 'three' 'ten' 'eleven']
test_score(out of 10): [ 8.  6. 10.  9.  7. nan]
interview_score(out of 10): [ 9  6  7 10  8]
salary($): [50000 45000 60000 65000 70000 62000 72000 80000]


In [24]:
df[df['test_score(out of 10)'].isnull()]

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
6        ten                    NaN                           7      72000

In [25]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [27]:
df=df.dropna()

In [28]:
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
7     eleven                    7.0                           8      80000

In [29]:
number_map = {
    'zero': 0,
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10,
    'eleven': 11,
    'twelve': 12
}

In [30]:
def convert_experience(exp):
    if exp.isdigit():
        return int(exp)
    return number_map.get(exp, None)

In [31]:
df['experience'] = df['experience'].apply(convert_experience)

C:\Users\Jaison\AppData\Local\Temp\ipykernel_1820\3530965482.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'] = df['experience'].apply(convert_experience)


In [32]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
7          11                    7.0                           8      80000

In [33]:
df.dtypes

experience                      int64
test_score(out of 10)         float64
interview_score(out of 10)      int64
salary($)                       int64
dtype: object

In [34]:
model = linear_model.LinearRegression()

In [37]:
model.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])
# or use 
#model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [38]:
model.coef_

array([2701.56191893, 2006.879881  , 1689.66158423])

In [39]:
model.intercept_

np.float64(22762.365191521014)

In [41]:
model.predict([[2,9,6]])

C:\Users\Jaison\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([56365.37746374])

In [42]:
model.predict([[12,10,10]])

C:\Users\Jaison\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92146.52287096])